{% set name = "sagemaker-pytorch-serving-container" %}
{% set version = "2.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2eb6fb5e3d5d1c3c3a4c2ae09e69404ec7e19372f2a62f3aaa76b3335a95d78a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - serve=sagemaker_pytorch_serving_container.serving:main
  noarch: python

requirements:
  host:
    - pip
    - python >=2.7,<3.7
  run:
    - python >=2.7,<3.7
    - numpy >=1.16.4
    - pillow >=6.2.0
    - retrying >=1.3.3
    - sagemaker_containers
    - six >=1.12.0
    - pytorch-cpu
    - requests-mock >=1.6.0
    - sagemaker-inference-toolkit
test:
  imports:
    - sagemaker_pytorch_serving_container

about:
  home: https://github.com/aws/sagemaker-pytorch-serving-container/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating PyTorch containers to run on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_pytorch.html
  dev_url: https://github.com/aws/sagemaker-pytorch-serving-container/

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - benhuff
    - oblute
