{% set name = "sagemaker-pytorch-serving-container" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b63d7c42b7861cad4428ff8eff795e561b368843fba038c159b96e3664a84bb4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - serve=sagemaker_pytorch_serving_container.serving:main
  noarch: python

requirements:
  host:
    - pip
    - python >=2.7,<3.7
  run:
    - python >=2.7,<3.7
    - numpy >=1.16.4
    - pillow >=6.2.0
    - retrying >=1.3.3
    - sagemaker_containers
    - six >=1.12.0
    - pytorch-cpu
    - requests-mock >=1.6.0
    - sagemaker-inference-toolkit
test:
  imports:
    - sagemaker_pytorch_serving_container

about:
  home: https://github.com/aws/sagemaker-pytorch-serving-container/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating PyTorch containers to run on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_pytorch.html
  dev_url: https://github.com/aws/sagemaker-pytorch-serving-container/

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
